const state={documents:[],documentId:null,workspace:null,activeRow:0,runId:null,saveToken:null,zoom:1,interactionStarted:new Map()};
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const payload=await r.json();if(!r.ok)throw new Error(`${payload.code||r.status}: ${payload.message||'request failed'}`);return payload}
function toast(message){$('toast').textContent=message;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',2600)}
async function refresh(){const h=await api('/api/health');$('badge').textContent=h.badge;$('identity').textContent=`${h.actor_id} · ${h.authentication}`;$('health').textContent=`DB ${h.db_integrity} · live ADA OFF`;state.documents=await api('/api/documents');renderDocuments();if(state.documentId)await openDocument(state.documentId)}
function renderDocuments(){ $('documents').innerHTML=state.documents.map(d=>`<div class="doc ${d.id===state.documentId?'active':''}" data-id="${d.id}"><b>${esc(d.invoice_number_normalized||d.source_filename)}</b><small>${esc(d.supplier_code||'กำลังอ่าน')} · ${esc(d.status)}</small><small>${d.grand_total_minor==null?'':(d.grand_total_minor/100).toFixed(2)+' THB'}</small></div>`).join('');document.querySelectorAll('.doc').forEach(n=>n.onclick=()=>openDocument(n.dataset.id))}
async function openDocument(id){const changed=state.documentId!==id;state.documentId=id;state.workspace=await api(`/api/workspace?document_id=${encodeURIComponent(id)}`);if(changed){state.activeRow=0;state.runId=null;state.saveToken=null}renderDocuments();renderWorkspace()}
function renderWorkspace(){const w=state.workspace,d=w.document;$('empty').hidden=true;$('workspace').hidden=false;$('doc-title').textContent=`${d.invoice_number_normalized} · ${(d.grand_total_minor/100).toFixed(2)} THB`;$('doc-status').className=`status ${d.status==='READY_FOR_ADA'||d.status==='COMPLETED'?'ok':''}`;$('doc-status').textContent=d.status;$('source').src=`/api/source?document_id=${encodeURIComponent(d.id)}`;$('headers').innerHTML=w.fields.map(f=>`<div class="field"><label>${esc(f.field_name)} · ${esc(f.review_status)}</label><input data-field="${esc(f.field_name)}" value="${esc(typeof f.final_value==='object'?JSON.stringify(f.final_value):f.final_value)}"><div class="actions"><button data-confirm-field="${esc(f.field_name)}">ยืนยัน</button><button data-correct-field="${esc(f.field_name)}">แก้ไข</button></div></div>`).join('');$('lines').innerHTML=w.lines.map((l,i)=>`<tr class="${i===state.activeRow?'active-row':''}" data-index="${i}" data-id="${l.id}"><td>${l.sequence}</td><td>${esc(l.raw_ocr_text)}</td><td><input data-product value="${esc(l.ada_product_code||'')}"></td><td><input data-unit value="${esc(l.ada_unit_code||l.unit_final||'')}"></td><td><input data-quantity value="${esc(l.quantity_decimal)}"></td><td>${(l.unit_price_minor/100).toFixed(2)}</td><td>${(l.line_total_minor/100).toFixed(2)}</td><td>${esc(l.review_status)}<br><button data-confirm-line>ยืนยัน</button><button data-correct-line>แก้ไข</button></td></tr>`).join('');$('issues').innerHTML=w.validation.issues.length?w.validation.issues.map(i=>`<div class="issue"><b>${esc(i.code)}</b> · expected ${esc(JSON.stringify(i.expected))}, observed ${esc(JSON.stringify(i.observed))}<br><small>${esc(i.safe_next_action)}</small></div>`).join(''):'<span class="status ok">ไม่มี blocking issue</span>';bindReview();$('authorize').disabled=!state.runId;$('save').disabled=!state.saveToken}
function durationFor(key){const started=state.interactionStarted.get(key)??performance.now();state.interactionStarted.delete(key);return Math.max(0,Math.round(performance.now()-started))}
function bindReview(){document.querySelectorAll('[data-field]').forEach(input=>input.onfocus=()=>state.interactionStarted.set(`field:${input.dataset.field}`,performance.now()));document.querySelectorAll('[data-product],[data-unit],[data-quantity]').forEach(input=>input.onfocus=()=>state.interactionStarted.set(`line:${input.closest('tr').dataset.id}`,performance.now()));document.querySelectorAll('[data-confirm-field]').forEach(b=>b.onclick=()=>reviewField(b.dataset.confirmField,'CONFIRM'));document.querySelectorAll('[data-correct-field]').forEach(b=>b.onclick=()=>reviewField(b.dataset.correctField,'CORRECT'));document.querySelectorAll('#lines tr').forEach(row=>{row.onclick=()=>{state.activeRow=Number(row.dataset.index);renderWorkspace()};row.querySelector('[data-confirm-line]').onclick=e=>{e.stopPropagation();reviewLine(row,'CONFIRM')};row.querySelector('[data-correct-line]').onclick=e=>{e.stopPropagation();reviewLine(row,'CORRECT')}})}
async function reviewField(name,action){const input=document.querySelector(`[data-field="${CSS.escape(name)}"]`);const original=state.workspace.fields.find(f=>f.field_name===name).final_value;let value=input.value;if(typeof original==='number')value=Number(value);await api('/api/review/header',{document_id:state.documentId,field_name:name,final_value:value,action,error_category:action==='CORRECT'?'OCR_ERROR':null,duration_ms:durationFor(`field:${name}`)});await openDocument(state.documentId)}
async function reviewLine(row,action){const product=row.querySelector('[data-product]').value,unit=row.querySelector('[data-unit]').value,quantity=row.querySelector('[data-quantity]').value,line=state.workspace.lines[Number(row.dataset.index)],duration=durationFor(`line:${row.dataset.id}`);if(quantity!==line.quantity_decimal)await api('/api/review/value',{document_id:state.documentId,line_id:row.dataset.id,field_name:'quantity',final_value:quantity,action:'CORRECT',error_category:'QUANTITY_EXTRACTION_ERROR',duration_ms:duration});await api('/api/review/product',{document_id:state.documentId,line_id:row.dataset.id,product_code:product,unit_code:unit,action,error_category:action==='CORRECT'?'SUPPLIER_ALIAS_UNKNOWN':null,duration_ms:duration});await openDocument(state.documentId)}
function move(delta){if(!state.workspace)return;state.activeRow=Math.max(0,Math.min(state.workspace.lines.length-1,state.activeRow+delta));renderWorkspace();document.querySelector(`tr[data-index="${state.activeRow}"]`)?.scrollIntoView({block:'nearest'})}
document.addEventListener('keydown',e=>{if(e.key==='ArrowDown'&&e.altKey){e.preventDefault();toast('แสดง provenance/candidates จาก prediction ที่ persist แล้ว')}else if(e.key==='ArrowDown'){e.preventDefault();move(1)}else if(e.key==='ArrowUp'){e.preventDefault();move(-1)}else if(e.key==='F8'){e.preventDefault();const issues=state.workspace?.validation.issues||[];toast(issues.length?issues[0].code:'ไม่มีปัญหาค้าง')}else if(e.key==='Enter'&&e.ctrlKey&&e.shiftKey&&state.workspace){e.preventDefault();const eligible=state.workspace.lines.filter(l=>l.current_prediction_id&&l.ada_product_code&&l.ada_unit_code&&l.review_status==='UNREVIEWED').map(l=>l.id);api('/api/review/bulk',{document_id:state.documentId,line_ids:eligible,duration_ms:750}).then(()=>openDocument(state.documentId)).catch(err=>toast(err.message))}else if(e.key==='Enter'&&e.ctrlKey&&state.workspace){e.preventDefault();const row=document.querySelector(`tr[data-index="${state.activeRow}"]`);if(row)reviewLine(row,'CONFIRM')}});
function asBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',',2)[1]);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
$('import-files').onclick=async()=>{try{const source=$('source-file').files[0],artifactFile=$('artifact-file').files[0];if(!source||!artifactFile)throw new Error('เลือกไฟล์ต้นฉบับและ reviewed OCR artifact');const artifact=JSON.parse(await artifactFile.text());const r=await api('/api/import',{source_name:source.name,source_base64:await asBase64(source),artifact});state.documentId=r.document_id;await refresh();toast(r.duplicate?'พบไฟล์เดิมและเปิดเอกสารเดิม':'นำเข้าและ persist predictions แล้ว')}catch(e){toast(e.message)}};$('ready').onclick=async()=>{try{await api('/api/ready',{document_id:state.documentId});await openDocument(state.documentId);toast('Ready for ADA')}catch(e){toast(e.message)}};
async function draft(driver){try{const r=await api('/api/ada/draft',{document_id:state.documentId,driver});state.runId=r.id;$('ada-log').textContent=JSON.stringify(r,null,2);$('authorize').disabled=r.state!=='AWAITING_HUMAN_SAVE';await openDocument(state.documentId);$('authorize').disabled=r.state!=='AWAITING_HUMAN_SAVE'}catch(e){toast(e.message)}}$('fake-draft').onclick=()=>draft('FAKE');$('replay-draft').onclick=()=>draft('REPLAY');$('authorize').onclick=async()=>{const r=await api('/api/ada/authorize',{run_id:state.runId});state.saveToken=r.token;$('save').disabled=false;toast('one-use token issued')};$('save').onclick=async()=>{try{const r=await api('/api/ada/save',{run_id:state.runId,token:state.saveToken});$('ada-log').textContent=JSON.stringify(r,null,2);$('save').disabled=true;await refresh()}catch(e){toast(e.message)}};
$('zoom-in').onclick=()=>{state.zoom=Math.min(2,state.zoom+.25);applyZoom()};$('zoom-out').onclick=()=>{state.zoom=Math.max(.5,state.zoom-.25);applyZoom()};function applyZoom(){$('source').style.width=`${state.zoom*100}%`;$('zoom-label').value=`${state.zoom*100}%`}
refresh().catch(e=>toast(e.message));
